# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/guides/getting-started/language-go/ for more details
version: 2.1

orbs:
  go: circleci/go@4.0.0

jobs:
  lint:
    executor:
      name: go/default
      tag: "1.26"
    steps:
      - checkout
      - go/with-cache:
          golangci-lint: true
          steps:
            - go/mod-download
            - run: golangci-lint run

  test:
    parameters:
      go-version:
        type: string
    machine:
      # https://circleci.com/docs/reference/configuration-reference/#available-linux-machine-images-cloud
      image: ubuntu-2604:2026.05.1
    # https://circleci.com/docs/reference/configuration-reference/#linuxvm-execution-environment
    resource_class: medium
    steps:
      - checkout
      - go/install:
          version: << parameters.go-version >>
      - go/with-cache:
          steps:
            - go/mod-download
            - run: make test

workflows:
  lint-and-test:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              go-version: ["1.26.4"]
