---
name: ci tests
discover: go list -f '{{ if or (len .TestGoFiles) (len .XTestGoFiles) }} {{ .ImportPath }} {{end}}' ./...
run: go tool gotestsum --junitfile="<< outputs.junit >>" -- -race -count=1 << test.atoms >>
analysis: go tool gotestsum -- -coverprofile="<< outputs.go-coverage >>" -cover -coverpkg ./... << test.atoms >>
options:
  dynamic-test-splitting: true
  max-auto-rerun: 3
  full-test-run-paths:
    - go.mod
    - .circleci/*.yml
outputs:
  junit: test-reports/tests.xml
